### ISSUE TITLE
How to pull data from other ArcGIS Dashboards

### ISSUE THREAD

**Issue by hawkseye76** [gohkokhan/covid19_JHU_dashboard#2]
Question, not issue.  Can you please explain how you derived the url for the data from the dashboard please?  I am wanting to pull State and County data from a dashboard as the source i have seems to be abandoned (which was the source csv for the dashboard)?

Any help is greatly appreciated. 

URL to dashboard i want data from:  https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7

Thanks

**Comment by gohkokhan** [comment]
Hi @pshellguruwannabe  You can try `curl 'https://services7.arcgis.com/4RQmZZ0yaZkGR1zy/arcgis/rest/services/COV19_Public_Dashboard_ReadOnly/FeatureServer/0/query?f=json&where=CONFIRMED%20%3E%200&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=69&cacheHint=true' -H 'authority: services7.arcgis.com' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36' -H 'sec-fetch-dest: empty' -H 'accept: */*' -H 'origin: https://alpublichealth.maps.arcgis.com' -H 'sec-fetch-site: same-site' -H 'sec-fetch-mode: cors' -H 'referer: https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html' -H 'accept-language: en,en-GB;q=0.9' -H 'if-none-match: sd140_-563924157' -H 'if-modified-since: Wed, 01 Apr 2020 00:30:11 GMT' --compressed`

The easiest method is to [inspect network activity](https://developers.google.com/web/tools/chrome-devtools/network)
The above link I was using this method. However, for JHU dashboard, the above method is not sufficient to provide what I want. hence I dive a little deeper to read the documentation of ArcGIS feature https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm
Then manually type in the query that I want. 
Hope it helps!

**Comment by hawkseye76** [comment]
Awesome!!  Thank you so much for the explanation!
